version: "3"
services:
  mongodb:
    image: mongo
    networks:
      - service-net
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - service-net
    ports:
      - 5672:5672
      - 15672:15672

  node-service:
    build: .
    environment:
      MONGO_URL: mongodb://mongodb:27017
      COLLECTION_NAME: table
      DB_NAME: mydb
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_EXCHANGE: hebele-hubele-exchange

    restart: unless-stopped
    networks:
      - service-net
    depends_on:
      - mongodb
      - rabbitmq

networks:
  service-net:
    driver: bridge
